---
format: html
tbl-colwidths: [15,10,5,5,5,20,10,30]
---

# Column Information of OpenLandMap GEDI Level 2

OpenLandMap GEDI Level 2 columns are selected from:

1.  LP DAAC GEDI02_A v002 (<https://lpdaac.usgs.gov/products/gedi02_av002/>) \[1\]
2.  LP DAAC GEDI02_B v002 (<https://lpdaac.usgs.gov/products/gedi02_bv002/>) \[2\]

*Table: OpenLandMap GEDI Level 2 Metadata, including scaling, no data, data type and description.*

+------------------------+------------+----------+-----------+---------------+----------------------------------+-------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Variable**           | **Source** | **Unit** | **Scale** | **Data type** | **Valid range (before scaling)** | **NoData**  | **Description / Usage**                                                                                                                                                                                                           |
+------------------------+------------+----------+-----------+---------------+----------------------------------+-------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Delta time             | L2A        | second   | N/A       | Int64         | N/A                              |             | Second count from 2018-01-01 00:00:00                                                                                                                                                                                             |
+------------------------+------------+----------+-----------+---------------+----------------------------------+-------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| beam                   | L2A        | number   | N/A       | Uint8         | 0 to 7                           | N/A         | Beam names as integers. BEAM0000 is a Coverage beam as 0;\                                                                                                                                                                        |
|                        |            |          |           |               |                                  |             | BEAM0001 is a Coverage beam as 1;\                                                                                                                                                                                                |
|                        |            |          |           |               |                                  |             | BEAM0010 is a Coverage beam as 2;\                                                                                                                                                                                                |
|                        |            |          |           |               |                                  |             | BEAM0011 is a Coverage beam as 3;\                                                                                                                                                                                                |
|                        |            |          |           |               |                                  |             | BEAM0101 is a Full power beam as 4;\                                                                                                                                                                                              |
|                        |            |          |           |               |                                  |             | BEAM0110 is a Full power beam as 5;\                                                                                                                                                                                              |
|                        |            |          |           |               |                                  |             | BEAM1000 is a Full power beam as 6;\                                                                                                                                                                                              |
|                        |            |          |           |               |                                  |             | BEAM1011 is a Full power beam as 7                                                                                                                                                                                                |
+------------------------+------------+----------+-----------+---------------+----------------------------------+-------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| shot_number            | L2A        | number   | N/A       | uint64        | N/A                              | N/A         | Shot number                                                                                                                                                                                                                       |
+------------------------+------------+----------+-----------+---------------+----------------------------------+-------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| latitude               | L2A        | N/A      | N/A       | Float64       | -55 to 55                        | na          | Latitude of the center of lowest mode in WGS84                                                                                                                                                                                    |
+------------------------+------------+----------+-----------+---------------+----------------------------------+-------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| longitude              | L2A        | N/A      | N/A       | Float64       | -180 to 180                      | na          | Longitude of the center of lowest mode in WGS84                                                                                                                                                                                   |
+------------------------+------------+----------+-----------+---------------+----------------------------------+-------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| elev_lowestmode        | L2A        | m        | 0.01      | Int32         | -100000 to 2500000               | -2147483648 | Elevation of lowest return/terrain height in WGS84                                                                                                                                                                                |
+------------------------+------------+----------+-----------+---------------+----------------------------------+-------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| rh100                  | L2A        | cm       | 0.01      | Int16         | -21300 to 21300                  | -32768      | Relative height values for the energy levels of 100%.                                                                                                                                                                             |
+------------------------+------------+----------+-----------+---------------+----------------------------------+-------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| rh99                   | L2A        | cm       | 0.01      | Int16         | -21300 to 21300                  | -32768      | Relative height values for the energy levels of 99%.                                                                                                                                                                              |
+------------------------+------------+----------+-----------+---------------+----------------------------------+-------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| rh98                   | L2A        | cm       | 0.01      | Int16         | -21300 to 21300                  | -32768      | Relative height values for the energy levels of 98%.                                                                                                                                                                              |
+------------------------+------------+----------+-----------+---------------+----------------------------------+-------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| rh97                   | L2A        | cm       | 0.01      | Int16         | -21300 to 21300                  | -32768      | Relative height values for the energy levels of 97%.                                                                                                                                                                              |
+------------------------+------------+----------+-----------+---------------+----------------------------------+-------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| rh95                   | L2A        | cm       | 0.01      | Int16         | -21300 to 21300                  | -32768      | Relative height values for the energy levels of 95%.                                                                                                                                                                              |
+------------------------+------------+----------+-----------+---------------+----------------------------------+-------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| rh75                   | L2A        | cm       | 0.01      | Int16         | -21300 to 21300                  | -32768      | Relative height values for the energy levels of 75%.                                                                                                                                                                              |
+------------------------+------------+----------+-----------+---------------+----------------------------------+-------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| rh50                   | L2A        | cm       | 0.01      | Int16         | -21300 to 21300                  | -32768      | Relative height values for the energy levels of 50%.                                                                                                                                                                              |
+------------------------+------------+----------+-----------+---------------+----------------------------------+-------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| rh25                   | L2A        | cm       | 0.01      | Int16         | -21300 to 21300                  | -32768      | Relative height values for the energy levels of 25%.                                                                                                                                                                              |
+------------------------+------------+----------+-----------+---------------+----------------------------------+-------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| sensitivity            | L2A        | percent  | 0.0001    | Int16         | 0 to 10000                       | -32768      | Maximum canopy cover that can be penetrated. Sensitivity has been pre-filtered by excluding \<95%.                                                                                                                                |
+------------------------+------------+----------+-----------+---------------+----------------------------------+-------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| night flag             | L2A        | binary   | N/A       | Boolean       | True, False                      | N/A         | Using solar elevation to flag day night (solar elevation \>=0: day; solar elevation \<0: night). Night=True and Day=False                                                                                                         |
+------------------------+------------+----------+-----------+---------------+----------------------------------+-------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| cover                  | L2B        | percent  | 0.0001    | Int16         | 0 to 10000                       | -32768      | Total canopy cover in percent.                                                                                                                                                                                                    |
+------------------------+------------+----------+-----------+---------------+----------------------------------+-------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| num_detectedmodes      | L2B        | number   | N/A       | Uint8         | 0 to 20                          | 255         | Number of detected modes in received (RX) waveform                                                                                                                                                                                |
+------------------------+------------+----------+-----------+---------------+----------------------------------+-------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| omega                  | L2B        | percent  | 0.0001    | Int16         | 0 to 10000                       | -32768      | Foliage Clumping Index                                                                                                                                                                                                            |
+------------------------+------------+----------+-----------+---------------+----------------------------------+-------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| pai                    | L2B        | m²/m²    | 0.001     | Int16         | N/A                              | -32768      | Total Plant Area Index                                                                                                                                                                                                            |
+------------------------+------------+----------+-----------+---------------+----------------------------------+-------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| pgap_theta             | L2B        | percent  | 0.0001    | Int16         | 0 to 10000                       | -32768      | Total Gap Probability (theta).                                                                                                                                                                                                    |
+------------------------+------------+----------+-----------+---------------+----------------------------------+-------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| rg                     | L2B        | number   | 0.1       | int32         | 0 to Inf                         | -2147483648 | Integral of the ground component in the RX waveform for the selected L2A processing version.                                                                                                                                      |
+------------------------+------------+----------+-----------+---------------+----------------------------------+-------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| rv                     | L2B        | number   | 0.1       | int32         | 0 to Inf                         | -2147483648 | Integral of the vegetation component in the RX waveform for the selected L2A processing version.                                                                                                                                  |
+------------------------+------------+----------+-----------+---------------+----------------------------------+-------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| rhog                   | L2B        | number   | 0.0001    | int16         | N/A                              | -32768      | Volumetric scattering coefficient (rho) of the ground.                                                                                                                                                                            |
+------------------------+------------+----------+-----------+---------------+----------------------------------+-------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| selected_rg_algorithm  | L2B        | number   | N/A       | uint8         | 0 to 6                           | 255         | Selected R (ground) algorithm                                                                                                                                                                                                     |
+------------------------+------------+----------+-----------+---------------+----------------------------------+-------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| rhov                   | L2B        | percent  | 0.0001    | Int16         | 0 to 10000                       | -32768      | Volumetric scattering coefficient (rho) of the canopy.                                                                                                                                                                            |
+------------------------+------------+----------+-----------+---------------+----------------------------------+-------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| selected_l2a_algorithm | L2B        | number   | N/A       | uint8         | 0 to 6                           | 255         | Selected L2A algorithm setting                                                                                                                                                                                                    |
+------------------------+------------+----------+-----------+---------------+----------------------------------+-------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| fhd_normal             | L2B        | index    | 0.01      | Int16         | N/A                              | -32768      | Foliage Height Diversity.                                                                                                                                                                                                         |
+------------------------+------------+----------+-----------+---------------+----------------------------------+-------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| surface_flag           | L2B        | binary   | N/A       | Boolean       | True, False                      | N/A         | Surface flag indicating if elev_lowestmode is within 300 m of DEM or MSS. True = within and False = outside                                                                                                                       |
+------------------------+------------+----------+-----------+---------------+----------------------------------+-------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| leaf_off_flag          | L2B        | binary   | N/A       | Boolean       | True, False                      | N/A         | GEDI 1 km EASE 2.0 grid flag derived from leaf_off_doy, leaf_on_doy and pft_class, indicating if the observation was recorded during leaf-off conditions in deciduous forests and woodlands. True = leaf-off and False = leaf-on. |
+------------------------+------------+----------+-----------+---------------+----------------------------------+-------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| l2b_quality_flag       | L2B        | binary   | N/A       | Boolean       | True, False                      | N/A         | L2B quality flag. True = qualified L2B points; False= not qualified L2B points                                                                                                                                                    |
+------------------------+------------+----------+-----------+---------------+----------------------------------+-------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| rh25_a1                | L2A        | m        | 0.01      | Int16         | -21300 to 21300                  | -32768      | Relative height values for the energy levels of 25% using the algorithm 1.                                                                                                                                                        |
+------------------------+------------+----------+-----------+---------------+----------------------------------+-------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| rh25_a2                | L2A        | m        | 0.01      | Int16         | -21300 to 21300                  | -32768      | Relative height values for the energy levels of 25% using the algorithm 1.                                                                                                                                                        |
+------------------------+------------+----------+-----------+---------------+----------------------------------+-------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| rh25_a3                | L2A        | m        | 0.01      | Int16         | -21300 to 21300                  | -32768      | Relative height values for the energy levels of 25% using the algorithm 3.                                                                                                                                                        |
+------------------------+------------+----------+-----------+---------------+----------------------------------+-------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| rh25_a4                | L2A        | m        | 0.01      | Int16         | -21300 to 21300                  | -32768      | Relative height values for the energy levels of 25% using the algorithm 4.                                                                                                                                                        |
+------------------------+------------+----------+-----------+---------------+----------------------------------+-------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| rh25_a5                | L2A        | m        | 0.01      | Int16         | -21300 to 21300                  | -32768      | Relative height values for the energy levels of 25% using the algorithm 5.                                                                                                                                                        |
+------------------------+------------+----------+-----------+---------------+----------------------------------+-------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| rh25_a6                | L2A        | m        | 0.01      | Int16         | -21300 to 21300                  | -32768      | Relative height values for the energy levels of 25% using the algorithm 6.                                                                                                                                                        |
+------------------------+------------+----------+-----------+---------------+----------------------------------+-------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| rh50_a1                | L2A        | m        | 0.01      | Int16         | -21300 to 21300                  | -32768      | Relative height values for the energy levels of 50% using the algorithm 1.                                                                                                                                                        |
+------------------------+------------+----------+-----------+---------------+----------------------------------+-------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| rh50_a2                | L2A        | m        | 0.01      | Int16         | -21300 to 21300                  | -32768      | Relative height values for the energy levels of 50% using the algorithm 2.                                                                                                                                                        |
+------------------------+------------+----------+-----------+---------------+----------------------------------+-------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| rh50_a3                | L2A        | m        | 0.01      | Int16         | -21300 to 21300                  | -32768      | Relative height values for the energy levels of 50% using the algorithm 3.                                                                                                                                                        |
+------------------------+------------+----------+-----------+---------------+----------------------------------+-------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| rh50_a4                | L2A        | m        | 0.01      | Int16         | -21300 to 21300                  | -32768      | Relative height values for the energy levels of 50% using the algorithm 4.                                                                                                                                                        |
+------------------------+------------+----------+-----------+---------------+----------------------------------+-------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| rh50_5N                | L2A        | m        | 0.01      | Int16         | -21300 to 21300                  | -32768      | Relative height values for the energy levels of 50% using the algorithm 5.                                                                                                                                                        |
+------------------------+------------+----------+-----------+---------------+----------------------------------+-------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| rh50_6N                | L2A        | m        | 0.01      | Int16         | -21300 to 21300                  | -32768      | Relative height values for the energy levels of 50% using the algorithm 6.                                                                                                                                                        |
+------------------------+------------+----------+-----------+---------------+----------------------------------+-------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| rh95_a1                | L2A        | m        | 0.01      | Int16         | -21300 to 21300                  | -32768      | Relative height values for the energy levels of 95% using the algorithm 1.                                                                                                                                                        |
+------------------------+------------+----------+-----------+---------------+----------------------------------+-------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| rh95_a2                | L2A        | m        | 0.01      | Int16         | -21300 to 21300                  | -32768      | Relative height values for the energy levels of 95% using the algorithm 2.                                                                                                                                                        |
+------------------------+------------+----------+-----------+---------------+----------------------------------+-------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| rh95_a3                | L2A        | m        | 0.01      | Int16         | -21300 to 21300                  | -32768      | Relative height values for the energy levels of 95% using the algorithm 3.                                                                                                                                                        |
+------------------------+------------+----------+-----------+---------------+----------------------------------+-------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| rh95_4a                | L2A        | m        | 0.01      | Int16         | -21300 to 21300                  | -32768      | Relative height values for the energy levels of 95% using the algorithm 4.                                                                                                                                                        |
+------------------------+------------+----------+-----------+---------------+----------------------------------+-------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| rh95_a5                | L2A        | m        | 0.01      | Int16         | -21300 to 21300                  | -32768      | Relative height values for the energy levels of 95% using the algorithm 5.                                                                                                                                                        |
+------------------------+------------+----------+-----------+---------------+----------------------------------+-------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| rh95_a6                | L2A        | m        | 0.01      | Int16         | -21300 to 21300                  | -32768      | Relative height values for the energy levels of 95% using the algorithm 6.                                                                                                                                                        |
+------------------------+------------+----------+-----------+---------------+----------------------------------+-------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| rh98_a1                | L2A        | m        | 0.01      | Int16         | -21300 to 21300                  | -32768      | Relative height values for the energy levels of 98% using the algorithm 1.                                                                                                                                                        |
+------------------------+------------+----------+-----------+---------------+----------------------------------+-------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| rh98_a2                | L2A        | m        | 0.01      | Int16         | -21300 to 21300                  | -32768      | Relative height values for the energy levels of 98% using the algorithm 2.                                                                                                                                                        |
+------------------------+------------+----------+-----------+---------------+----------------------------------+-------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| rh98_a3                | L2A        | m        | 0.01      | Int16         | -21300 to 21300                  | -32768      | Relative height values for the energy levels of 98% using the algorithm 3.                                                                                                                                                        |
+------------------------+------------+----------+-----------+---------------+----------------------------------+-------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| rh98_a4                | L2A        | m        | 0.01      | Int16         | -21300 to 21300                  | -32768      | Relative height values for the energy levels of 98% using the algorithm 4.                                                                                                                                                        |
+------------------------+------------+----------+-----------+---------------+----------------------------------+-------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| rh98_a5                | L2A        | m        | 0.01      | Int16         | -21300 to 21300                  | -32768      | Relative height values for the energy levels of 98% using the algorithm 5.                                                                                                                                                        |
+------------------------+------------+----------+-----------+---------------+----------------------------------+-------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| rh98_a6                | L2A        | m        | 0.01      | Int16         | -21300 to 21300                  | -32768      | Relative height values for the energy levels of 98% using the algorithm 6.                                                                                                                                                        |
+------------------------+------------+----------+-----------+---------------+----------------------------------+-------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| rh99_1a                | L2A        | m        | 0.01      | Int16         | -21300 to 21300                  | -32768      | Relative height values for the energy levels of 99% using the algorithm 1.                                                                                                                                                        |
+------------------------+------------+----------+-----------+---------------+----------------------------------+-------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| rh99_2a                | L2A        | m        | 0.01      | Int16         | -21300 to 21300                  | -32768      | Relative height values for the energy levels of 99% using the algorithm 2.                                                                                                                                                        |
+------------------------+------------+----------+-----------+---------------+----------------------------------+-------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| rh99_3a                | L2A        | m        | 0.01      | Int16         | -21300 to 21300                  | -32768      | Relative height values for the energy levels of 99% using the algorithm 3.                                                                                                                                                        |
+------------------------+------------+----------+-----------+---------------+----------------------------------+-------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| rh99_4a                | L2A        | m        | 0.01      | Int16         | -21300 to 21300                  | -32768      | Relative height values for the energy levels of 99% using the algorithm 4.                                                                                                                                                        |
+------------------------+------------+----------+-----------+---------------+----------------------------------+-------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| rh99_5a                | L2A        | m        | 0.01      | Int16         | -21300 to 21300                  | -32768      | Relative height values for the energy levels of 99% using the algorithm 5.                                                                                                                                                        |
+------------------------+------------+----------+-----------+---------------+----------------------------------+-------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| rh99_6a                | L2A        | m        | 0.01      | Int16         | -21300 to 21300                  | -32768      | Relative height values for the energy levels of 99% using the algorithm 6.                                                                                                                                                        |
+------------------------+------------+----------+-----------+---------------+----------------------------------+-------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| elev_lowestmode_a1a    | L2A        | m        | 0.01      | Int32         | -100000 to 2500000               | -2147483648 | Elevation of lowest return/terrain height in WGS84 using algorithm 1                                                                                                                                                              |
+------------------------+------------+----------+-----------+---------------+----------------------------------+-------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| elev_lowestmode_2a     | L2A        | m        | 0.01      | Int32         | -100000 to 2500000               | -2147483648 | Elevation of lowest return/terrain height in WGS84 using algorithm 2                                                                                                                                                              |
+------------------------+------------+----------+-----------+---------------+----------------------------------+-------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| elev_lowestmode_3a     | L2A        | m        | 0.01      | Int32         | -100000 to 2500000               | -2147483648 | Elevation of lowest return/terrain height in WGS84 using algorithm 3                                                                                                                                                              |
+------------------------+------------+----------+-----------+---------------+----------------------------------+-------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| elev_lowestmode_4a     | L2A        | m        | 0.01      | Int32         | -100000 to 2500000               | -2147483648 | Elevation of lowest return/terrain height in WGS84 using algorithm 4                                                                                                                                                              |
+------------------------+------------+----------+-----------+---------------+----------------------------------+-------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| elev_lowestmode_5a     | L2A        | m        | 0.01      | Int32         | -100000 to 2500000               | -2147483648 | Elevation of lowest return/terrain height in WGS84 using algorithm 5                                                                                                                                                              |
+------------------------+------------+----------+-----------+---------------+----------------------------------+-------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| elev_lowestmode_6a     | L2A        | m        | 0.01      | Int32         | -100000 to 2500000               | -2147483648 | Elevation of lowest return/terrain height in WGS84 using algorithm 6                                                                                                                                                              |
+------------------------+------------+----------+-----------+---------------+----------------------------------+-------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| sensitivity_1a         | L2A        | percent  | 0.0001    | Int16         | 0 to 10000                       | -32768      | Maximum canopy cover using algorithms 1 that can be penetrated.                                                                                                                                                                   |
+------------------------+------------+----------+-----------+---------------+----------------------------------+-------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| sensitivity_2a         | L2A        | percent  | 0.0001    | Int16         | 0 to 10000                       | -32768      | Maximum canopy cover using algorithms 2 that can be penetrated.                                                                                                                                                                   |
+------------------------+------------+----------+-----------+---------------+----------------------------------+-------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| sensitivity_3a         | L2A        | percent  | 0.0001    | Int16         | 0 to 10000                       | -32768      | Maximum canopy cover using algorithms 3 that can be penetrated.                                                                                                                                                                   |
+------------------------+------------+----------+-----------+---------------+----------------------------------+-------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| sensitivity_4a         | L2A        | percent  | 0.0001    | Int16         | 0 to 10000                       | -32768      | Maximum canopy cover using algorithms 4 that can be penetrated.                                                                                                                                                                   |
+------------------------+------------+----------+-----------+---------------+----------------------------------+-------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| sensitivity_5a         | L2A        | percent  | 0.0001    | Int16         | 0 to 10000                       | -32768      | Maximum canopy cover using algorithms 5 that can be penetrated.                                                                                                                                                                   |
+------------------------+------------+----------+-----------+---------------+----------------------------------+-------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| sensitivity_6a         | L2A        | percent  | 0.0001    | Int16         | 0 to 10000                       | -32768      | Maximum canopy cover using algorithms 6 that can be penetrated.                                                                                                                                                                   |
+------------------------+------------+----------+-----------+---------------+----------------------------------+-------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+

: {.striped .hover}

### Reference

*1. Dubayah, R., Hofton, M., Blair, J., Armston, J., Tang, H., Luthcke, S. (2021). GEDI L2A Elevation and Height Metrics Data Global Footprint Level V002 \[Data set\]. NASA EOSDIS Land Processes Distributed Active Archive Center. <https://doi.org/10.5067/GEDI/GEDI02_A.002.>*

*2. Dubayah, R., Tang, H., Armston, J., Luthcke, S., Hofton, M., Blair, J. (2021). GEDI L2B Canopy Cover and Vertical Profile Metrics Data Global Footprint Level V002 \[Data set\]. NASA EOSDIS Land Processes Distributed Active Archive Center. <https://doi.org/10.5067/GEDI/GEDI02_B.002.>*